"""
train.py — Load dataset arrays and train the model.

Expects X_train.npy / y_train.npy / X_val.npy / y_val.npy under SAVE_DIR
(generated by dataset.py).

Usage:
    python train.py
"""

import os
import json
import numpy as np
import tensorflow as tf
from tensorflow.keras import callbacks

from config import SAVE_DIR, EPOCHS, BATCH_SIZE
from model import build_model


# ── Load data ─────────────────────────────────────────────────────────────────

X_train = np.load(os.path.join(SAVE_DIR, "X_train.npy"))
y_train = np.load(os.path.join(SAVE_DIR, "y_train.npy"))
X_val   = np.load(os.path.join(SAVE_DIR, "X_val.npy"))
y_val   = np.load(os.path.join(SAVE_DIR, "y_val.npy"))

with open(os.path.join(SAVE_DIR, "labels.json"), encoding="utf-8") as f:
    actions = json.load(f)

num_classes = len(actions)
print(f"Classes ({num_classes}): {actions}")
print(f"X_train {X_train.shape} | X_val {X_val.shape}")


# ── Build model ───────────────────────────────────────────────────────────────

model = build_model(num_classes=num_classes)
model.summary()


# ── Callbacks ─────────────────────────────────────────────────────────────────

checkpoint = callbacks.ModelCheckpoint(
    filepath=os.path.join(SAVE_DIR, "best_model.keras"),
    monitor="val_loss",
    save_best_only=True,
    verbose=1,
)

reduce_lr = callbacks.ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.5,
    patience=5,
    min_lr=1e-6,
    verbose=1,
)


# ── Train ─────────────────────────────────────────────────────────────────────

history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    callbacks=[checkpoint, reduce_lr],
)

# Save final weights (best checkpoint is already saved by ModelCheckpoint)
model.save(os.path.join(SAVE_DIR, "final_model.keras"))
print(f"\n✅  Training complete.")
print(f"    Best model  → {SAVE_DIR}/best_model.keras")
print(f"    Final model → {SAVE_DIR}/final_model.keras")

# Save history for later plotting
np.save(os.path.join(SAVE_DIR, "history.npy"), history.history)
